# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: philip.stroemert@tib.eu
full_name: Philip Strömert
gh_action_docs_preview: true
gh_action_pypi: true
github_org: NFDI4Chem
license: MIT
project_description: 'This is a DCAT Application Profile extension that formalizes
    the NFDI4Chem Minimum information about chemical investigation stAndard foR reportinG
    liquid-stAte nmR experImenTs of smAll moleculeS (MARGARITAS). '
project_name: nmr-dcat-ap
project_slug: nmr_dcat_ap

